# Generated by Django 5.1.6 on 2025-02-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='caregory',
            new_name='category',
        ),
    ]
